name: Project auto-testing
on:
  workflow_run:
    workflows: ["Polybot Service Deployment"]
    types:
      - completed

permissions: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ec2_ip: ${{ steps.set_ip.outputs.ec2_ip }}
    steps:
      - name: Fetch EC2 Public IP
        id: set_ip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          IP=$(aws ec2 describe-instances --instance-ids i-0598dd777bcbfdf21 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
          if [ $? -eq 0 ]; then
            echo "::set-output name=ec2_ip::$IP"
          else
            echo "AWS CLI command failed:"
            echo $IP
            exit 1
          fi
  on-success:
    runs-on: ubuntu-latest
    needs:
      - setup
    env:
      EC2_PUBLIC_IP: ${{ needs.setup.outputs.ec2_ip }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Test Docker Compose project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            curl -O -L https://raw.githubusercontent.com/alonitac/PolybotServiceDocker/main/test/test-compose-project.sh
            bash test-compose-project.sh

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo "Your Polybot Service Deployment workflow should be completed successfully first"
          exit 1